# Generated by Django 3.2 on 2023-06-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(
                default=0, verbose_name='Кол-во'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(
                db_index=True, max_length=200, verbose_name='Название'
            ),
        ),
    ]
